//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanDo.Areas.Admin.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            HinhAnh = "fileName.jpg";
            this.ChiTietHangDat = new HashSet<ChiTietHangDat>();
        }
    
        public int id { get; set; }
        public Nullable<int> idLoai { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public string MoTa { get; set; }
        public string ThongTinChiTiet { get; set; }
        public string TenVietTat { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHangDat> ChiTietHangDat { get; set; }
    }
}
